# Generated by Django 5.2.17 on 2026-08-25 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='단지명')),
                ('region', models.CharField(choices=[('common', '전국 공통'), ('seoul', '서울'), ('cheonan', '천안'), ('busan_namgu', '부산 남구'), ('incheon_michuhol', '인천 미추홀구'), ('sejong', '세종'), ('jeju', '제주')], db_index=True, max_length=50, verbose_name='지역')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='주소')),
                ('resident_code', models.CharField(max_length=20, verbose_name='입주 인증 코드')),
                ('is_registered', models.BooleanField(default=True, verbose_name='단지 존재 확인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '아파트 단지',
                'verbose_name_plural': '아파트 단지',
                'db_table': 'apartments',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', '음식물'), ('recycle', '재활용'), ('bulky', '대형폐기물'), ('time', '배출시간'), ('place', '배출장소'), ('etc', '기타')], max_length=20, verbose_name='분류')),
                ('content', models.TextField(verbose_name='규정 내용')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='apartment_rules/%Y/%m/', verbose_name='배출장소 사진')),
                ('source_level', models.CharField(choices=[('official', '관리사무소·규약'), ('resident', '입주민 제보')], max_length=20, verbose_name='출처 등급')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('review', '검토대기'), ('approved', '승인'), ('rejected', '반려')], db_index=True, default='draft', max_length=20, verbose_name='상태')),
                ('confirm_count', models.PositiveIntegerField(default=0, verbose_name='확인 수')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='적용 시작일')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='적용 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='apartments.apartment', verbose_name='단지')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_by_rules', to='rag.document', verbose_name='연동 문서')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='제안자')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='apartments.apartmentrule', verbose_name='대체 규정')),
            ],
            options={
                'verbose_name': '단지 규정',
                'verbose_name_plural': '단지 규정',
                'db_table': 'apartment_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('resident', '입주민'), ('manager', '관리사무소 관리자')], max_length=20, verbose_name='역할')),
                ('status', models.CharField(choices=[('requested', '신청'), ('approved', '승인'), ('rejected', '거절'), ('terminated', '해지')], db_index=True, default='requested', max_length=20, verbose_name='상태')),
                ('is_primary', models.BooleanField(default=False, verbose_name='기본 단지')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='승인/거절 사유')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='apartments.apartment', verbose_name='단지')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_memberships', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '단지 소속',
                'verbose_name_plural': '단지 소속',
                'db_table': 'apartment_memberships',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='apartments.apartmentrule')),
            ],
            options={
                'db_table': 'apartment_rule_confirmations',
            },
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='uq_apartment_name_region'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('member', 'apartment', 'role'), name='uq_membership_member_apartment_role'),
        ),
        migrations.AddConstraint(
            model_name='ruleconfirmation',
            constraint=models.UniqueConstraint(fields=('rule', 'member'), name='uq_confirmation_rule_member'),
        ),
    ]
