# Generated by Django 5.2.17 on 2026-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='resident_code',
        ),
    ]
