# Generated by Django 5.2.17 on 2026-08-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_apartment_resident_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentrule',
            name='confirm_count',
        ),
        migrations.DeleteModel(
            name='RuleConfirmation',
        ),
    ]
