# Generated by Django 5.2.17 on 2026-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartmentrule_confirm_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='office_hours',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='운영시간'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='관리사무소 전화번호'),
        ),
        migrations.AddField(
            model_name='apartmentrule',
            name='source_file',
            field=models.FileField(blank=True, help_text='PDF/txt/md 파일을 올리면 규정 내용이 자동으로 채워집니다.', null=True, upload_to='apartment_rules/source/%Y/%m/', verbose_name='규정 원문 파일'),
        ),
        migrations.AlterField(
            model_name='apartmentrule',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='규정 내용'),
        ),
    ]
