# Generated by Django 5.2.17 on 2026-08-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_office_hours_apartment_office_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrule',
            name='category',
            field=models.CharField(choices=[('place_time', '배출 장소/시간'), ('method', '처리 방식'), ('cost_admin', '비용/행정'), ('facility', '단지 특수 시설'), ('etc', '기타')], max_length=20, verbose_name='분류'),
        ),
    ]
