# Generated by Django 5.2.17 on 2026-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('region', models.CharField(choices=[('common', '전국 공통'), ('seoul', '서울'), ('cheonan', '천안'), ('busan_namgu', '부산 남구'), ('incheon_michuhol', '인천 미추홀구'), ('sejong', '세종'), ('jeju', '제주')], default='seoul', max_length=50, verbose_name='지역')),
                ('has_answer', models.BooleanField(default=True, verbose_name='답변 성공')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='질문 시각')),
            ],
            options={
                'verbose_name': '질문 로그',
                'verbose_name_plural': '질문 로그',
                'db_table': 'chat_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '챗봇')], max_length=20, verbose_name='발화자')),
                ('content', models.TextField(verbose_name='본문')),
                ('tip', models.TextField(blank=True, default='', verbose_name='실천 팁')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='근거 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '대화 메시지',
                'verbose_name_plural': '대화 메시지',
                'db_table': 'chat_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='비어 있으면 첫 질문을 잘라서 표시합니다.', max_length=100, verbose_name='대화방 제목')),
                ('region', models.CharField(choices=[('common', '전국 공통'), ('seoul', '서울'), ('cheonan', '천안'), ('busan_namgu', '부산 남구'), ('incheon_michuhol', '인천 미추홀구'), ('sejong', '세종'), ('jeju', '제주')], default='seoul', help_text='이 대화방에서 사용하는 지역. 기본값은 회원 프로필의 region 입니다.', max_length=50, verbose_name='지역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
            ],
            options={
                'verbose_name': '대화방',
                'verbose_name_plural': '대화방',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
