# Generated by Django 5.2.17 on 2026-08-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartmentrule_confirm_count_and_more'),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apartments.apartment', verbose_name='단지'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='law_notice',
            field=models.TextField(blank=True, default='', verbose_name='법령 시행 안내'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='suggested_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='추천 질문'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apartments.apartment', verbose_name='단지'),
        ),
    ]
