# Generated by Django 5.2.17 on 2026-08-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatlog_apartment_chatmessage_law_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', '좋아요'), ('negative', '싫어요')], db_index=True, max_length=10, null=True, verbose_name='피드백'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='피드백 시각'),
        ),
    ]
