# Generated by Django 5.2.17 on 2026-08-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatlog_region_alter_chatsession_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='contact_cards',
            field=models.JSONField(blank=True, default=list, verbose_name='연락처 카드'),
        ),
    ]
