# Generated by Django 5.2.17 on 2026-08-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.TextField(verbose_name='대표 질문')),
                ('embedding', models.TextField(verbose_name='대표 벡터(JSON)')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='질문 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '질문 클러스터',
                'verbose_name_plural': '질문 클러스터',
                'db_table': 'question_clusters',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content_text', models.TextField(blank=True, default='', verbose_name='본문')),
                ('source_type', models.CharField(choices=[('law', '법령 원문'), ('guide', '배출 가이드'), ('manual', '사용자 업로드')], db_index=True, default='manual', max_length=20, verbose_name='문서 종류')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='원본 링크')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='원본 파일')),
                ('region', models.CharField(blank=True, choices=[('common', '전국 공통'), ('seoul', '서울'), ('cheonan', '천안'), ('busan_namgu', '부산 남구'), ('incheon_michuhol', '인천 미추홀구'), ('sejong', '세종'), ('jeju', '제주')], db_index=True, help_text='비어 있거나 common 이면 전국 공통으로 취급합니다.', max_length=50, null=True, verbose_name='적용 지역')),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='원본 파일 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(blank=True, help_text='사용자가 올린 문서만 채워집니다. 공용 문서는 비어 있습니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
                'db_table': 'documents',
                'ordering': ['source_type', 'title'],
                'indexes': [models.Index(fields=['owner', 'source_type'], name='doc_owner_type_idx')],
            },
        ),
    ]
