# Generated by Django 5.2.17 on 2026-08-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartmentrule_confirm_count_and_more'),
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apartment',
            field=models.ForeignKey(blank=True, help_text='source_type=apartment 문서만 채워집니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apartments.apartment', verbose_name='단지'),
        ),
        migrations.AddField(
            model_name='document',
            name='law_amendment_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='개정 구분'),
        ),
        migrations.AddField(
            model_name='document',
            name='law_doc_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='법령/고시 번호'),
        ),
        migrations.AddField(
            model_name='document',
            name='law_effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='시행일'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', '작성중'), ('approved', '승인')], db_index=True, default='approved', max_length=20, verbose_name='색인 상태'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('law', '법령 원문'), ('guide', '배출 가이드'), ('manual', '사용자 업로드'), ('apartment', '아파트 단지 규정')], db_index=True, default='manual', max_length=20, verbose_name='문서 종류'),
        ),
    ]
