# Generated by Django 5.2.17 on 2026-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_document_apartment_document_law_amendment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReindexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirty', models.BooleanField(default=False, verbose_name='갱신 대기')),
                ('status', models.CharField(choices=[('idle', '대기'), ('running', '색인 중'), ('failed', '실패')], default='idle', max_length=20, verbose_name='상태')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='요청 사유')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='요청 시각')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='마지막 오류')),
                ('last_result', models.JSONField(blank=True, default=dict, verbose_name='마지막 결과')),
            ],
            options={
                'verbose_name': '재색인 상태',
                'verbose_name_plural': '재색인 상태',
                'db_table': 'reindex_state',
            },
        ),
    ]
