# Generated by Django 5.2.17 on 2026-08-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_document_region'),
        ('rag', '0003_reindexstate'),
    ]

    operations = [
    ]
