# Generated by Django 5.2.17 on 2026-08-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartmentrule_confirm_count_and_more'),
        ('boards', '0003_board_category_board_comment_count_board_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='apartments.apartment', verbose_name='단지'),
        ),
    ]
