# Generated by Django 5.2.17 on 2026-08-25 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_apartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='비공개 처리일'),
        ),
        migrations.AddField(
            model_name='board',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='비공개 처리자'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='관리자가 비공개 처리한 글. 목록에서 일반 사용자에게 숨겨집니다.', verbose_name='비공개'),
        ),
    ]
