# Generated by Django 5.2.17 on 2026-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_hidden_at_board_hidden_by_board_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('notice', '공지'), ('question', '질문'), ('info', '정보공유'), ('review', '후기'), ('free', '자유')], db_index=True, default='free', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='board',
            name='region',
            field=models.CharField(choices=[('common', '전국 공통'), ('seoul', '서울'), ('cheonan', '천안'), ('busan_namgu', '부산 남구'), ('incheon_michuhol', '인천 미추홀구'), ('sejong', '세종'), ('jeju', '제주'), ('daegu', '대구'), ('daejeon', '대전'), ('suwon', '수원'), ('ulsan', '울산')], db_index=True, default='common', help_text='어느 지역 기준의 글인지. 검색 시 지역 필터에 쓰입니다.', max_length=50, verbose_name='지역'),
        ),
    ]
