# Generated by Django 5.2.17 on 2026-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='커뮤니티·챗봇에서 표시되는 이름입니다.', max_length=30, verbose_name='닉네임'),
        ),
    ]
