# Generated by Django 5.2.17 on 2026-08-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='', help_text='커뮤니티·챗봇에서 표시되는 이름입니다.', max_length=30, verbose_name='닉네임'),
        ),
    ]
